### ISSUE TITLE
Option to specify flyctl version

### ISSUE THREAD

**Issue by amithm7** [superfly/flyctl-actions#10]
Considering flyctl is in rapid development, actions were broken for few days where `FLY_APP` env. variable was not picked up.

And it throws errors like these, which doesn't point out the problem.

```
WARN no config file found at /github/home/.fly/config.yml
Error we couldn't find a fly.toml nor an app specified by the -a flag. If you want to launch a new app, use 'flyctl launch'
```

This issue was however fixed few hours ago: https://github.com/superfly/flyctl/commit/7015ec3e6e1b7053f5b817a9e0976e1f4f0e9462

To avoid such issues, please create a [input](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsstepswith) to specify version. For example:

```yml
with:
  version: a.b.c
```

**Comment by jsierles** [comment]
We'd now probably have to do #12 before we could do this, as I don't think you can pass build args to Docker actions.

**Comment by jsierles** [comment]
This is now possible using work done in #12.
