### ISSUE TITLE
CI runs interrupting a deploy cause the CI run to fail

### ISSUE THREAD

**Issue by charsleysa** [superfly/flyctl-actions#18]
When a CI run that deploys to fly.io starts before a previous deployment finishes, the new deployment takes over and completes successfully but fly ends up generating an error and the CI run ends in failure even though the deployment was successful.

Can this be changed so that it no longer throws an error if the deployment completed successfully?

**Comment by jsierles** [comment]
Can you provide more details about this error?

**Comment by charsleysa** [comment]
This issue is over a year old and I don't even know if it's still an issue so I'm gonna close this for now. If it's still an issue I'll open a new one.
