### ISSUE TITLE
Please, create a major version tag for these actions

### ISSUE THREAD

**Issue by madhead** [superfly/flyctl-actions#33]
First of all, thank you for the Fly.io! I wish you good traction and stable growth!

One way to achieve that is developers' adoption. And these actions are good example of caring about us, developers.

But I humbly plead for more.

There is project [krzema12/github-workflows-kt](https://github.com/krzema12/github-workflows-kt) that allows you to write action using Kotlin DSL, a statically typed language, preferred by some over the YAML. It doesn't require action's authors to change anything in their actions to be supported. Only types could be optionally provided, but it's not an issue yet.

One thing that this project requires, however, is the existing of major version tags in the actions it supports. Examples are:

- [actions/checkout@v3](https://github.com/actions/checkout/tree/v3)
- [actions/setup-node@v3](https://github.com/actions/setup-node/tree/v3)
- [actions/cache@v3](https://github.com/actions/cache/tree/v3)

You got the idea, a `v3` tag always points to the latest `v3.x` version, whatever it is. It first points to the `v3.0.0`, but then you release `v3.0.1` and move the `v3` to point on it, then you release `v3.1.0` and update the `v3` again, etc…

Can you please add this major version tag in this repository? Thanks!

cc: @krzema12
context: https://github.com/krzema12/github-workflows-kt/issues/595

**Comment by jsierles** [comment]
v1 was created and pinned to the release of  v1.4. Thanks!
