### ISSUE TITLE
-r or --region flags not working in ci on flyctl deploy

### ISSUE THREAD

**Issue by benonymus** [superfly/flyctl-actions#37]
It seems like the region flag do not work (or unreliably) in Github Actions.

In my workflow I create an app, and deploy to that app with the flag.
The deployment ends up in random regions.
It seems impossible to set the region beforehand because -y is not supported which is needed for custom names.

**Comment by jsierles** [comment]
With new V2 platform apps, this should not be a problem. V1 (nomad) is deprecated and shouldn't be used in new apps. Cheers.
