### ISSUE TITLE
Is it possible for this to use a different fly.toml/Procfile?

### ISSUE THREAD

**Issue by Kyu** [superfly/flyctl-actions#41]
e.g fly.toml.dev and Procfile.dev for dev environment testing

**Comment by murmrs** [comment]
On the run command here:

```
- run: flyctl deploy --remote-only
```

You can pass specific configs using `--config`. Eg;

```
- run: flyctl deploy --remote-only --config ./fly.production.toml
```

 See [kere](https://fly.io/docs/flyctl/deploy/).

**Comment by Kyu** [comment]
Thank you! I'll test it out
