### ISSUE TITLE
`flyctl certs list --json` not working in GitHub Action

### ISSUE THREAD

**Issue by tomy0000000** [superfly/flyctl-actions#43]
I deployed fly apps with GitHub Action and wrote a small script to export the environment URL for GitHub. However, the CI returns an error saying that the `--json` flag does not exist.

Check out the `🔗 Fetch Environment URL` step [here](https://github.com/tomy0000000/appshelf/actions/runs/4708132191/jobs/8350389661)

Can confirm this works perfectly locally, just can't get it working on CI. Is there any difference between `fly`/`flyctl` and the version provided locally and in the cloud?

**Comment by tomy0000000** [comment]
@jsierles sorry for bothering you, but can you take a look at this small issue? Many thanks 🙏

**Comment by jsierles** [comment]
Is this still happening?  Can you paste the full command you're trying to run?

**Comment by tomy0000000** [comment]
> Is this still happening? Can you paste the full command you're trying to run?

Full command is `flyctl certs list --json`

You can find the error [here](https://github.com/tomy0000000/appshelf/actions/runs/4708132191/jobs/8350389661#step:5:2)

the weird thing is that `fly certs list --json` runs perfect on the local, but fails in GitHub action

**Comment by jsierles** [comment]
It's possible that was a regression in the version you had. Can you try again with the latest? It looks like your action is now failing because you don't have your fly auth token set.

**Comment by tomy0000000** [comment]
> It's possible that was a regression in the version you had. Can you try again with the latest? It looks like your action is now failing because you don't have your fly auth token set.

I just rerun with the latest master, and [it says](https://github.com/tomy0000000/appshelf/actions/runs/4925091490/jobs/8845800978#step:3:6) it's using version 0.1.0, which doesn't seems normal.

Can confirm the missing auth token is the cause [here](https://github.com/tomy0000000/appshelf/actions/runs/4925091490/jobs/8845800978#step:5:5).

But I'm quite sure I have the `FLY_API_TOKEN` setup.

<img width="789" alt="CleanShot 2023-05-11 at 18 09 32@2x" src="https://github.com/superfly/flyctl-actions/assets/23290356/3b23de41-4ef9-4e7e-b389-e69eb89b173b">

Most importantly, the deployment went smoothly.

Do you think anything is missing here?

**Comment by jsierles** [comment]
Nope, looks good! v0.1.0 is correct - it's the first new minor version. Before that, we used `0.0.x`.
