### ISSUE TITLE
Latest update broke -e env var passing

### ISSUE THREAD

**Issue by benonymus** [superfly/flyctl-actions#45]
Hey,

Since the last update our deployments that use the `-e` flag fail.
https://fly.io/docs/flyctl/deploy/#usage

Any idea why?

**Comment by benonymus** [comment]
Thanks for the quick fix! Seems to work!

**Comment by jsierles** [comment]
This was a regression in flyctl `0.1.2`. `0.1.3` fixes it - can you confirm?

**Comment by benonymus** [comment]
Yes, a bit earlier I pinned the flyctl version to `0.0.558` and it worked.
Then I checked the flyctl releases and saw `0.1.3` pinned that (then removed it) and it is works.
