### ISSUE TITLE
Please remove/rename `v2` branch

### ISSUE THREAD

**Issue by mfinelli** [superfly/flyctl-actions#46]
There is an (old) branch on this repository named `v2` which causes @dependabot to think that there is an update to this action and propose a pull request when in fact that branch is older than the latest `v1` release. Please rename or remove this old branch so that dependabot will stop being confused. Thanks

**Comment by smorimoto** [comment]
+1

**Comment by matthewlehner** [comment]
I've jut removed the v2 branch. Hopefully this helps!
