### ISSUE TITLE
github actions npm install error : deploy requires npm 9.7.1

### ISSUE THREAD

**Issue by josh-boat365** [superfly/flyctl-actions#47]
name: Fly Deploy
on: [push]
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl deploy

**Comment by josh-boat365** [comment]
---> 0e44d5beaea4
Step 8/20 : RUN if grep -Fq "laravel/octane" /var/www/html/composer.json; then         rm -rf /etc/supervisor/conf.d/fpm.conf;         if grep -Fq "spiral/roadrunner" /var/www/html/composer.json; then             mv /etc/supervisor/octane-rr.conf /etc/supervisor/conf.d/octane-rr.conf;             if [ -f ./vendor/bin/rr ]; then ./vendor/bin/rr get-binary; fi;             rm -f .rr.yaml;         else             mv .fly/octane-swoole /etc/services.d/octane;             mv /etc/supervisor/octane-swoole.conf /etc/supervisor/conf.d/octane-swoole.conf;         fi;         rm /etc/nginx/sites-enabled/default;         ln -sf /etc/nginx/sites-available/default-octane /etc/nginx/sites-enabled/default;     fi
 ---> Running in 4decc8e8717b
 ---> cee205a77482
Step 9/20 : FROM node:${NODE_VERSION} as node_modules_go_brrr
 ---> 8e81ac769c95
Step 10/20 : RUN mkdir /app
 ---> Running in cf7f4c71f2fe
 ---> b494afa5205c
Step 11/20 : RUN mkdir -p  /app
 ---> Running in c5c1fd403f07
 ---> 0fec39600704
Step 12/20 : WORKDIR /app
 ---> Running in eec0ae070ed8
 ---> b264f813451d
Step 13/20 : COPY . .
 ---> b97bc7cbb309
Step 14/20 : COPY --from=base /var/www/html/vendor /app/vendor
 ---> 0f67ad444d01
Step 15/20 : RUN if [ -f "vite.config.js" ]; then         ASSET_CMD="build";     else         ASSET_CMD="production";     fi;     if [ -f "yarn.lock" ]; then         yarn install --frozen-lockfile;         yarn $ASSET_CMD;     elif [ -f "pnpm-lock.yaml" ]; then         corepack enable && corepack prepare pnpm@latest-7 --activate;         pnpm install --frozen-lockfile;         pnpm run $ASSET_CMD;     elif [ -f "package-lock.json" ]; then         npm ci --no-audit;         npm run $ASSET_CMD;     else         npm install;         npm run $ASSET_CMD;     fi;
 ---> Running in 1743fc30a899

added 121 packages in 3s

21 packages are looking for funding
  run `npm fund` for details
npm notice 
npm notice New minor version of npm available! 9.5.1 -> 9.7.2
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.7.2>
npm notice Run `npm install -g npm@9.7.2` to update!
npm notice 

> build
> vite build

vite v4.3.9 building for production...
transforming...
✓ 141 modules transformed.
rendering chunks...
computing gzip size...
public/build/manifest.json                                 2.28 kB │ gzip:  0.44 kB
public/build/assets/fa-v4compatibility-694a17c3.woff2      4.56 kB
public/build/assets/fa-v4compatibility-0515a423.ttf       10.17 kB
public/build/assets/fa-regular-400-8e7e5ea1.woff2         24.95 kB
public/build/assets/fa-regular-400-528d022d.ttf           63.95 kB
public/build/assets/fa-brands-400-74833209.woff2         108.02 kB
public/build/assets/QuartzoBold-a49e010d.ttf             120.99 kB
public/build/assets/fa-solid-900-7152a693.woff2          150.12 kB
public/build/assets/Raleway-Medium-f5a6dcd3.ttf          163.39 kB
public/build/assets/fa-brands-400-20c4a58b.ttf           187.21 kB
public/build/assets/fa-solid-900-67a65763.ttf            394.63 kB
public/build/assets/bg5-638a9482.jpg                   1,000.88 kB
public/build/assets/app-f41b20e1.css                      48.68 kB │ gzip:  8.06 kB
public/build/assets/all.min-9c157fb8.css                  88.36 kB │ gzip: 22.54 kB
public/build/assets/app-e6e3ba2a.js                      130.98 kB │ gzip: 39.83 kB
✓ built in 3.85s
 ---> e52bd167c186
Step 16/20 : FROM base
 ---> cee205a77482
Step 17/20 : COPY --from=node_modules_go_brrr /app/public /var/www/html/public-npm
 ---> f2db2ad570c5
Step 18/20 : RUN rsync -ar /var/www/html/public-npm/ /var/www/html/public/     && rm -rf /var/www/html/public-npm     && chown -R www-data:www-data /var/www/html/public
 ---> Running in 95c8025de93b
 ---> 5bd11453e042
Step 19/20 : EXPOSE 8080
 ---> Running in 4a679aaedd57
 ---> 0639416a759e
Step 20/20 : ENTRYPOINT ["/entrypoint"]
 ---> Running in a2d014d347ea
 ---> 4fae3f3ec8cb
Successfully built 4fae3f3ec8cb
Successfully tagged registry.fly.io/iams:deployment-01H3FPZ57Q2EGSNXQRB5EVRA2Y
--> Building image done
==> Pushing image to fly
The push refers to repository [registry.fly.io/iams]
da9a08f06fc3: Preparing
056f14f1ae1b: Preparing
a7aafd344d69: Preparing
d2863dfa1bd2: Preparing
1e1d406868d2: Preparing
73c5d014ae43: Preparing
b09e013fce59: Preparing
be770e8d11d6: Preparing
c1e35a4376ec: Preparing
eb348aa3ee27: Preparing
0e2541556835: Preparing
d5dbb4093dc9: Preparing
6f37ca73c74f: Preparing
73c5d014ae43: Waiting
b09e013fce59: Waiting
be770e8d11d6: Waiting
c1e35a4376ec: Waiting
eb348aa3ee27: Waiting
0e2541556835: Waiting
d5dbb4093dc9: Waiting
6f37ca73c74f: Waiting
1e1d406868d2: Layer already exists
73c5d014ae43: Layer already exists
b09e013fce59: Layer already exists
be770e8d11d6: Layer already exists
c1e35a4376ec: Layer already exists
eb348aa3ee27: Layer already exists
0e2541556835: Layer already exists
d5dbb4093dc9: Layer already exists
da9a08f06fc3: Pushed
d2863dfa1bd2: Pushed
056f14f1ae1b: Pushed
a7aafd344d69: Pushed
6f37ca73c74f: Pushed
deployment-01H3FPZ57Q2EGSNXQRB5EVRA2Y: digest: sha256:638ca5cf832b0e360b3b2d2531e11b483cef0400e1bdc862938280b337f1a99c size: 3041
--> Pushing image done
image: registry.fly.io/iams:deployment-01H3FPZ57Q2EGSNXQRB5EVRA2Y

image size: 364 MB
Watch your app at https://fly.io/apps/iams/monitoring

Running iams release_command: php /var/www/html/artisan migrate --force
  Created release_command machine 9080575f637148
  Waiting for 9080575f637148 to have state: started
  Machine 9080575f637148 has state: started
  Waiting for 9080575f637148 to have state: destroyed
  Machine 9080575f637148 has state: destroyed
  Waiting for 9080575f637148 to get exit event
Error release_command failed running on machine 9080575f637148 with exit code 1.
Check its logs: here's the last 100 lines below, or run 'fly logs -i 9080575f637148':
  Pulling container image registry.fly.io/iams:deployment-01H3FPZ57Q2EGSNXQRB5EVRA2Y
  Successfully prepared image registry.fly.io/iams:deployment-01H3FPZ57Q2EGSNXQRB5EVRA2Y (5.171238624s)
  Configuring firecracker
   INFO Starting init (commit: 0b28cec)...
   INFO Preparing to run: `/entrypoint php /var/www/html/artisan migrate --force` as root
   INFO [fly api proxy] listening at /.fly/api
  2023/06/21 19:31:41 listening on [fdaa:2:6409:a7b:bbfa:6e0b:ea64:2]:22 (DNS: [fdaa::3]:53)
  {"message":"SQLSTATE[HY000] [2002] Connection refused (Connection: mysql, SQL: select * from information_schema.tables where table_schema = forge and table_name = migrations and table_type = 'BASE TABLE')","context":{"exception":{"class":"Illuminate\\Database\\QueryException","message":"SQLSTATE[HY000] [2002] Connection refused (Connection: mysql, SQL: select * from information_schema.tables where table_schema = forge and table_name = migrations and table_type = 'BASE TABLE')","code":2002,"file":"/var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:795","previous":{"class":"PDOException","message":"SQLSTATE[HY000] [2002] Connection refused","code":2002,"file":"/var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:65"}}},"level":400,"level_name":"ERROR","channel":"production","datetime":"2023-06-21T19:31:43.362855+00:00","extra":{}}
  In Connection.php line 795:
    SQLSTATE[HY000] [2002] Connection refused (Connection: mysql, SQL: select *
     from information_schema.tables where table_schema = forge and table_name =
     migrations and table_type = 'BASE TABLE')
  In Connector.php line 65:
    SQLSTATE[HY000] [2002] Connection refused
   INFO Main child exited normally with code: 1
   INFO Starting clean up.
   WARN hallpass exited, pid: 514, status: signal: 15 (SIGTERM)
  2023/06/21 19:31:43 listening on [fdaa:2:6409:a7b:bbfa:6e0b:ea64:2]:22 (DNS: [fdaa::3]:53)
  [    3.133835] reboot: Restarting system
  machine restart policy set to 'no', not restarting
Error: release command failed - aborting deployment. error release_command machine 9080575f637148 exited with non-zero status of 1

Error: Process completed with exit code 1.

**Comment by jsierles** [comment]
This issue is framework specific and not related to flyctl-actions. Do try posting on https://community.fly.io!
