### ISSUE TITLE
Environment variables are not inherited into fly deploy/build context

### ISSUE THREAD

**Issue by ajsharp** [superfly/flyctl-actions#5]
I'm trying to use this to deploy a rails app. The app is using the heroku buildpack, and requires certain environment variables to be set while building assets 🤦 

I have those variables set in the github actions environment, but when `rake assets:precompile` runs, it can't see them, and the script blows up.

**Comment by jsierles** [comment]
Sorry we missed this. Did you figure it out? `flyctl` won't inherit environment variables, generally. To use them during a build, you'd need to set build arguments. This can be done on the command line or in `fly.toml`. See https://fly.io/docs/reference/configuration/#build-args
