### ISSUE TITLE
`v1` tag is not current with the `1.5` minor version

### ISSUE THREAD

**Issue by jbcaprell** [superfly/flyctl-actions#54]
Hey, guys! I was setting up a workflow, and had intended to set up this step similarly to others like:

https://github.com/erlef/setup-beam/tree/v1
https://github.com/actions/setup-node/tree/v4
https://github.com/actions/checkout/tree/v4
https://github.com/actions/cache/tree/v4

… but the ‘equivalent’ tag, `v1`, is not current with the minor version (`1.5`) like other GitHub Action-adjacent repositories; it’s still back at `v1.4`.

**Comment by jsierles** [comment]
Done!
