### ISSUE TITLE
v2 release deleted?

### ISSUE THREAD

**Issue by indirect** [superfly/flyctl-actions#58]
A few weeks ago, Dependabot sent me a PR to upgrade this action to the release tagged v2, and we merged it and have been using it for a while. Today, my deploy pipeline that uses this action just started failing, and the v2 tag we were using appears to have been deleted. Is deleting existing releases after a few weeks going to be a thing going forward?

**Comment by jsierles** [comment]
I'm not sure that release was created intentionally. The [1.5](https://github.com/superfly/flyctl-actions/releases/tag/1.5) release is up to date with master. @matthewlehner do you have any insight here?

**Comment by matthewlehner** [comment]
Yes, there was an old branch named `v2` that was quite far behind our current v1.5 release. I removed it in the last week or so as it was causing dependabot issues for other folks.


For reference, here's the issue that prompted removing it:
https://github.com/superfly/flyctl-actions/issues/46

@indirect can you use the v1 tag?

**Comment by indirect** [comment]
Ah, that explains it! Dependabot told me to "upgrade", so I'm glad to learn it was not actually an intended release. Thanks.
