### ISSUE TITLE
Cannot use from monorepo with project in subdirectory

### ISSUE THREAD

**Issue by SimeonGriggs** [superfly/flyctl-actions#7]
Would it be possible to extend support of the action to enable deploying from a subdirectory in a mono repo?

**Comment by fedeotaran** [comment]
Hi! You have to set a `FLY_PROJECT_PATH` env. I found this recently!

Look at this file:
https://github.com/superfly/flyctl-actions/blob/master/entrypoint.sh#L3-L7
